version: '3.8'

services:
  web:
    image: node:18
    ports:
      - "3000:3000"
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    command: >
      sh -c "npm install && npm start"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongo:27017/mydatabase

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: